name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 8.4
  #         tools: composer:v2
  #         coverage: xdebug

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'
  #         cache: 'npm'

  #     - name: Install Node Dependencies
  #       run: npm ci

  #     - name: Build Assets
  #       run: npm run build

  #     - name: Install Dependencies
  #       run: composer install --no-interaction --prefer-dist --optimize-autoloader

  #     - name: Copy Environment File
  #       run: cp .env.example .env

  #     - name: Generate Application Key
  #       run: php artisan key:generate

  #     - name: Tests
  #       run: ./vendor/bin/pest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install dependencies and build
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Deploy public/ to public_html/
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /
          local-dir: ./public/

      - name: Deploy app files to home directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ../
          local-dir: ./
          exclude: |
            public/
            node_modules/
            .git/
            .github/
            tests/
            ...
