name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Lint all PHP files
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install dependencies and build
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Lint all PHP files
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: Check Laravel boots without errors
        run: php artisan

      - name: Deploy public/ to public_html/
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ./
          local-dir: ./public/

      - name: Deploy app files to home directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ../
          local-dir: ./
          exclude: |
            **/node_modules/**
            **/.git/**
            **/.github/**
            **/tests/**
            **/public/**
            **/vendor/**

      - name: SSH and run composer install
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          port: ${{ vars.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd domains/admin.sachsevent.com/
            composer2 install --no-dev --optimize-autoloader

      - name: SSH and run migrations
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          port: ${{ vars.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd domains/admin.sachsevent.com/
            php artisan migrate --force
